name: blue_print_pos_example
description: Demonstrates how to use the blue_print_pos plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  blue_print_pos:
    path: ../

  flutter:
    sdk: flutter
  flutter_widget_from_html: ^0.10.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/logo.jpg